on:
  push:
    branches:
      - main

jobs:
  run_deployment:
    name: run deployment
    runs-on: ubuntu-latest

    steps:
      - name: install ssh-key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo $PATH && source \$HOME/.cargo/env && ./deploy.sh && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
